language: php

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^analysis-.*$/
    - /^patch-.*$/

php:
    - 5.6
    - 7.0
    - 7.1
env:
  global:
    - TEST_COMMAND="bin/behat"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - $TEST_COMMAND
